name: env-test

on:
  push:
    branches:
      - "main"
env:
  DB_HOST: ${{ secrets.DB_HOST }}
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 # buildx 설정        
      -
        name: Dokcker Build
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            BUILDKIT_PROGRESS=plain
            DB_HOST =${{ secrets.DB_HOST }}
